### ISSUE TITLE
Unable to load username or message status

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink-Mobile#102]
**Device**: Samsung Galaxy A71

**Browser**: Chrome

**Issue**: When a user creates an account and login. When they go to the Profile page the Username and Status will appear as "It was not possible to load the username It was not possible to load the message status" 

**How to replicate**: 
1. Create an account
2. Navigate to Profile

**Screenshot**: 
![image](https://user-images.githubusercontent.com/93608357/189413591-68d4ff91-155f-49d2-aab1-105973df382d.png)

**Comment by lgmarchi** [comment]
@phillsatellite This problem is happening yet because the update of the libraries to use raygun for chat messages. 

Thanks to report this, I believe it will be fixed after the PR with 12 words passphrase

**Comment by lgmarchi** [comment]
@phillsatellite Are you having this problem yet?

**Comment by phillsatellite** [comment]
@lgmarchi  could no longer replicate, gonna move this issue to closed for now 👍
