### ISSUE TITLE
Some Account Phrases are not appearing while importing account

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink-Mobile#103]
**Device:** Samsung Galaxy A71 
**Browser:** Chrome
**Issue:** Seems some of the Account Phrases a user will be given are missing when trying to import account. I was given the word _Paint_ but when I try to add that phrase while Importing Account it does not appear on the suggested phrases and won't let user hit enter 
**How to replicate:** 
1. Create an account 
2. Log out and go to importing account and attempt to put in every phrase 
**Screen recording:**

https://user-images.githubusercontent.com/93608357/189763323-675bd601-bac3-44e4-aff9-8822e2fed58b.mp4

**Comment by hyj1204** [comment]
**Paint** is not a word in BIP39 dictionary. The PR 104 implements the real recovery seeds words from the warp, so all the word show on the recovery seeds page will belong to BIP39. After the PR 104 merged, this issue will go away.
