### ISSUE TITLE
File: Add UI for Files page

### ISSUE THREAD

**Issue by tooshel** [Satellite-im/Uplink-Mobile#115]
File UI note:
https://satellite.wiki/s/05435d28-69d1-43a1-bdd1-3ba82347bced

Migrated from: https://satellite-im.atlassian.net/browse/UL-189

**Comment by hyj1204** [comment]
[115-photo-preview-and-options](https://github.com/Satellite-im/Uplink/tree/115-photo-preview-and-options)
Favorite item/photo and Favorites List
![image](https://user-images.githubusercontent.com/14248245/194913836-b540643b-0236-4a33-8fa4-d5e4abb46239.png)
![image](https://user-images.githubusercontent.com/14248245/194913779-48a5c3cf-61e9-4dad-917a-4423d1e269f1.png)
![image](https://user-images.githubusercontent.com/14248245/194913806-31908658-09e9-4823-8d31-e535d3095786.png)

**Comment by hyj1204** [comment]
[115-photo-preview-and-options](https://github.com/Satellite-im/Uplink/tree/115-photo-preview-and-options)
Remove item/photo and remove list
![image](https://user-images.githubusercontent.com/14248245/194914045-c4c50605-f995-47c5-8afb-2d32ad41d609.png)
![image](https://user-images.githubusercontent.com/14248245/194914083-129bd874-45f0-4577-b38b-8fbdd0c0fa90.png)

**Comment by hyj1204** [comment]
[115-photo-preview-and-options](https://github.com/Satellite-im/Uplink/tree/115-photo-preview-and-options)
Preview the photo, rename photo and delete
![image](https://user-images.githubusercontent.com/14248245/194914701-643c5954-b0cc-4042-9522-583d31875e81.png)
![image](https://user-images.githubusercontent.com/14248245/194914810-d318f28a-ac62-4281-a48a-bde154b2f4bc.png)
